import navigation from './navigation'
import band from './band'
import footer from './footer'
import album from './album'
import hero from './hero'
import home from './home'
import music from './music'
import gigs from './gigs'
import merch from './merch'
import merchProduct from './merchProduct'
import merchContent from './merchContent'
import merchOrder from './merchOrder'
import legal from './legal'
import contact from './contact'

export const schemaTypes = [navigation, band, footer, album, hero, home, music, gigs, merch, merchProduct, merchContent, merchOrder, legal, contact]
